/*
 * A small, local-only presentation fixture. It keeps the demo button useful
 * without requiring a GitHub token or an LLM provider key. Live audits always
 * come from the FastAPI endpoints.
 */
window.DEMO_DATA = {
  run: {
    id: "demo-audit-2026-08-31",
    repository_url: "https://github.com/demo/payment-service",
    requested_ref: "release/v1.4",
    commit_sha: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
    status: "completed",
    final_decision: "NO-GO",
    started_at: "2026-08-31T14:32:01Z",
    finished_at: "2026-08-31T14:34:18Z",
    runtime_ms: 137000,
    estimated_cost_usd: 0.11,
    model_id: "releaseguard-offline-v1",
    prompt_version: "final-v2",
    system_version: "0.1.0",
    mode: "final",
  },
  report: {
    schema_version: "1.0",
    audit_run_id: "demo-audit-2026-08-31",
    repository_url: "https://github.com/demo/payment-service",
    requested_ref: "release/v1.4",
    commit_sha: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
    mode: "final",
    decision: "NO-GO",
    executive_summary:
      "The release gate is closed because a confirmed CI configuration issue prevents the release workflow from running on release branches. One production environment mismatch needs human review. Eight standard compliance checks passed.",
    findings: [
      {
        id: "F-001",
        audit_run_id: "demo-audit-2026-08-31",
        category: "ci",
        title: "Release workflow does not run on release branch",
        severity: "critical",
        claim:
          "The production workflow only declares main as a push branch. The requested release/v1.4 ref is therefore not covered by the configured trigger, so the deployment path is not exercised for this release.",
        confidence: 0.99,
        evidence_ids: ["E-014"],
        recommended_action:
          "Update the workflow trigger configuration to include release/* under branches, then rerun the release checks for the immutable commit.",
        verification_status: "confirmed",
        origin: "analyzer",
      },
      {
        id: "F-002",
        audit_run_id: "demo-audit-2026-08-31",
        category: "config",
        title: "Production environment contract has an unresolved mismatch",
        severity: "high",
        claim:
          "The release workflow references PAYMENT_GATEWAY_URL while the production environment declaration exposes PAYMENT_API_URL. The evidence is strong, but ownership of the runtime contract needs a human decision before release.",
        confidence: 0.86,
        evidence_ids: ["E-016"],
        recommended_action:
          "Align the workflow and production environment variable names, or document the translation layer and add a smoke check.",
        verification_status: "needs_human_review",
        origin: "analyzer",
      },
      {
        id: "F-003",
        audit_run_id: "demo-audit-2026-08-31",
        category: "dependencies",
        title: "Deprecated dependency candidate",
        severity: "high",
        claim:
          "The dependency scan surfaced an older logging package in the manifest.",
        confidence: 0.62,
        evidence_ids: ["E-003"],
        recommended_action: "Review the dependency graph before the next release.",
        verification_status: "rejected",
        origin: "analyzer",
      },
    ],
    rejected_findings: [
      {
        id: "F-003",
        audit_run_id: "demo-audit-2026-08-31",
        category: "dependencies",
        title: "Deprecated dependency candidate",
        severity: "high",
        claim:
          "The dependency scan surfaced an older logging package in the manifest.",
        confidence: 0.62,
        evidence_ids: ["E-003"],
        recommended_action: "Review the dependency graph before the next release.",
        verification_status: "rejected",
        origin: "analyzer",
      },
    ],
    verifications: [
      {
        finding_id: "F-001",
        status: "confirmed",
        confidence: 0.99,
        supporting_evidence: ["E-014"],
        contradicting_evidence: [],
        reason_summary:
          "The cited workflow restricts push triggers to main. No alternative release workflow was found in the snapshot.",
        verifier_error: null,
      },
      {
        finding_id: "F-003",
        status: "rejected",
        confidence: 0.91,
        supporting_evidence: [],
        contradicting_evidence: ["E-003"],
        reason_summary:
          "The container layer removes the flagged class before packaging; the manifest signal is not release-blocking.",
        verifier_error: null,
      },
    ],
    evidence: [
      {
        id: "E-001",
        audit_run_id: "demo-audit-2026-08-31",
        source_type: "test_result",
        source_path: "test_report",
        source_ref: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
        line_start: null,
        line_end: null,
        content_hash:
          "sha256:2621d90d51855a1a34a3ee870d9cd3f455e670861b45f0c722ed58fd96e0d0d4",
        summary: "Test report: 84/84 passed, 0 failed",
        payload: {
          report: { total: 84, passed: 84, failed: 0, failures: [] },
          test_files: ["tests/test_payment_gateway.py", "tests/test_checkout.py"],
        },
      },
      {
        id: "E-003",
        audit_run_id: "demo-audit-2026-08-31",
        source_type: "github_file",
        source_path: "pom.xml",
        source_ref: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
        line_start: 42,
        line_end: 48,
        content_hash:
          "sha256:3a5fb48a5ad621c50cf0b1adbdf6302886248420a44d2be1244110050bb50253",
        summary: "Read dependency declaration from pom.xml",
        payload: {
          path: "pom.xml",
          start_line: 42,
          end_line: 48,
          total_lines: 112,
          content:
            "42 | <dependency>\n43 |   <groupId>org.legacy</groupId>\n44 |   <artifactId>legacy-log</artifactId>\n45 |   <version>1.2.0</version>\n46 | </dependency>",
        },
      },
      {
        id: "E-014",
        audit_run_id: "demo-audit-2026-08-31",
        source_type: "github_file",
        source_path: ".github/workflows/release.yml",
        source_ref: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
        line_start: 12,
        line_end: 22,
        content_hash:
          "sha256:4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8091a2b3c4d5e6f7",
        summary: "Read file .github/workflows/release.yml (lines 12-22)",
        payload: {
          path: ".github/workflows/release.yml",
          start_line: 12,
          end_line: 22,
          total_lines: 38,
          content:
            "12 | name: Production Release\n13 |\n14 | on:\n15 |   push:\n16 |     branches:\n17 |       - main\n18 |\n19 | jobs:\n20 |   deploy:\n21 |     runs-on: ubuntu-latest\n22 |     environment: production",
        },
      },
      {
        id: "E-016",
        audit_run_id: "demo-audit-2026-08-31",
        source_type: "github_file",
        source_path: "deploy/production.env.example",
        source_ref: "a83f92c19d7e4b2c17f08f5a91c3d6e0a6d8f124",
        line_start: 1,
        line_end: 12,
        content_hash:
          "sha256:7c10b3d91c5f4f2f8c5e35e9c9f7a36f5a2b1c8d4e6f0a1b3c5d7e9f1a2b4c6d",
        summary: "Read production environment declaration",
        payload: {
          path: "deploy/production.env.example",
          start_line: 1,
          end_line: 12,
          total_lines: 12,
          content:
            "1 | PAYMENT_API_URL=https://api.example.internal\n2 | PAYMENT_TIMEOUT_MS=2500\n3 | PAYMENT_REGION=us-east-1",
        },
      },
    ],
    deterministic_checks: [
      {
        check_id: "DC-01",
        name: "Test configuration and execution",
        status: "pass",
        details: "84/84 tests passed; no test failures recorded.",
        evidence_ids: ["E-001"],
      },
      {
        check_id: "DC-02",
        name: "CI workflow presence",
        status: "pass",
        details: "2 workflow files found.",
        evidence_ids: ["E-014"],
      },
      {
        check_id: "DC-03",
        name: "CI release-ref trigger configuration",
        status: "fail",
        details: "release/v1.4 is not included in release workflow push branches.",
        evidence_ids: ["E-014"],
      },
      {
        check_id: "DC-04",
        name: "Latest CI run status for release ref",
        status: "pass",
        details: "Latest recorded CI run concluded success.",
        evidence_ids: ["E-001"],
      },
      {
        check_id: "DC-05",
        name: "Release version metadata consistency",
        status: "pass",
        details: "Manifest and tag versions match.",
        evidence_ids: [],
      },
      {
        check_id: "DC-06",
        name: "Lockfile presence",
        status: "warn",
        details: "A dependency manifest exists but no lockfile was detected.",
        evidence_ids: [],
      },
      {
        check_id: "DC-07",
        name: "Build/release command",
        status: "pass",
        details: "Release build report completed successfully.",
        evidence_ids: [],
      },
      {
        check_id: "DC-08",
        name: "Secret scan",
        status: "pass",
        details: "No known secret patterns detected in scanned files.",
        evidence_ids: [],
      },
    ],
    limitations: [
      "The demo is a local fixture and does not contact GitHub.",
      "Human review remains required for unresolved environment contracts.",
    ],
    runtime_ms: 137000,
    model_id: "releaseguard-offline-v1",
    prompt_version: "final-v2",
    estimated_cost_usd: 0.11,
  },
  trajectory: [
    {
      sequence: 1,
      component: "orchestrator",
      state: "snapshot",
      tool: "create_workspace_snapshot",
      output_summary: "Resolved release/v1.4 to immutable commit a83f92c1.",
      evidence_created: [],
      duration_ms: 820,
      status: "success",
      timestamp: "2026-08-31T14:32:05Z",
    },
    {
      sequence: 2,
      component: "tools",
      state: "check",
      tool: "run_all_checks",
      output_summary: "Completed 8 deterministic checks; 1 fail and 1 warning.",
      evidence_created: ["E-001", "E-014"],
      duration_ms: 2840,
      status: "success",
      timestamp: "2026-08-31T14:32:10Z",
    },
    {
      sequence: 3,
      component: "analyzer",
      state: "finding",
      tool: "read_file",
      output_summary: "Created finding F-001: release trigger does not cover release branches.",
      evidence_created: ["E-014"],
      duration_ms: 6100,
      status: "success",
      timestamp: "2026-08-31T14:32:18Z",
    },
    {
      sequence: 4,
      component: "analyzer",
      state: "finding",
      tool: "read_file",
      output_summary: "Created finding F-002: production environment variable mismatch.",
      evidence_created: ["E-016"],
      duration_ms: 3900,
      status: "success",
      timestamp: "2026-08-31T14:32:25Z",
    },
    {
      sequence: 5,
      component: "verifier",
      state: "verify",
      tool: "search_repository",
      output_summary: "Confirmed F-001; no contradicting workflow was found.",
      evidence_created: [],
      duration_ms: 12100,
      status: "success",
      timestamp: "2026-08-31T14:33:08Z",
    },
    {
      sequence: 6,
      component: "orchestrator",
      state: "report",
      tool: "apply_decision_policy",
      output_summary: "Decision policy returned NO-GO for 1 confirmed critical finding.",
      evidence_created: [],
      duration_ms: 160,
      status: "success",
      timestamp: "2026-08-31T14:34:18Z",
    },
  ],
  evaluation: {
    meta: {
      run_label: "final_2026-08-31_demo",
      mode: "final",
      model_id: "releaseguard-offline-v1",
      execution_mode: "offline_fixture",
      cases_total: 12,
    },
    aggregate: {
      development: {
        cbr: 1,
        precision: 1,
        f1: 1,
        decision_accuracy: 1,
        critical_evidence_coverage: 1,
        total_runtime_ms: 494,
      },
      held_out: {
        cbr: 1,
        precision: 1,
        f1: 1,
        decision_accuracy: 1,
        critical_evidence_coverage: 1,
        total_runtime_ms: 288,
      },
      all: {
        cbr: 1,
        precision: 1,
        f1: 1,
        decision_accuracy: 1,
        critical_evidence_coverage: 1,
        total_runtime_ms: 782,
      },
    },
    results: [
      ["case_01", "GO", "GO", "PASS"],
      ["case_02", "NO-GO", "NO-GO", "PASS"],
      ["case_03", "NO-GO", "NO-GO", "PASS"],
      ["case_04", "REVIEW", "REVIEW", "PASS"],
      ["case_05", "NO-GO", "NO-GO", "PASS"],
      ["case_06", "NO-GO", "NO-GO", "PASS"],
      ["case_07", "NO-GO", "NO-GO", "PASS"],
      ["case_08", "REVIEW", "REVIEW", "PASS"],
      ["case_09", "NO-GO", "NO-GO", "PASS"],
      ["case_10", "NO-GO", "NO-GO", "PASS"],
      ["case_11", "NO-GO", "NO-GO", "PASS"],
      ["case_12", "NO-GO", "NO-GO", "PASS"],
    ],
  },
};
